/* Auto-generated by genmsg_cpp for file /home/dukerama/sandbox/irobot_create_2_1/srv/Brake.srv */
#ifndef IROBOT_CREATE_2_1_SERVICE_BRAKE_H
#define IROBOT_CREATE_2_1_SERVICE_BRAKE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace irobot_create_2_1
{
template <class ContainerAllocator>
struct BrakeRequest_ {
  typedef BrakeRequest_<ContainerAllocator> Type;

  BrakeRequest_()
  : brake(false)
  {
  }

  BrakeRequest_(const ContainerAllocator& _alloc)
  : brake(false)
  {
  }

  typedef uint8_t _brake_type;
  uint8_t brake;


  typedef boost::shared_ptr< ::irobot_create_2_1::BrakeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_create_2_1::BrakeRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BrakeRequest
typedef  ::irobot_create_2_1::BrakeRequest_<std::allocator<void> > BrakeRequest;

typedef boost::shared_ptr< ::irobot_create_2_1::BrakeRequest> BrakeRequestPtr;
typedef boost::shared_ptr< ::irobot_create_2_1::BrakeRequest const> BrakeRequestConstPtr;



template <class ContainerAllocator>
struct BrakeResponse_ {
  typedef BrakeResponse_<ContainerAllocator> Type;

  BrakeResponse_()
  : success(false)
  {
  }

  BrakeResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::irobot_create_2_1::BrakeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::irobot_create_2_1::BrakeResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BrakeResponse
typedef  ::irobot_create_2_1::BrakeResponse_<std::allocator<void> > BrakeResponse;

typedef boost::shared_ptr< ::irobot_create_2_1::BrakeResponse> BrakeResponsePtr;
typedef boost::shared_ptr< ::irobot_create_2_1::BrakeResponse const> BrakeResponseConstPtr;


struct Brake
{

typedef BrakeRequest Request;
typedef BrakeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Brake
} // namespace irobot_create_2_1

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::irobot_create_2_1::BrakeRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::irobot_create_2_1::BrakeRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::irobot_create_2_1::BrakeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "691501d2b5eb4dc01a97397d7baf5fba";
  }

  static const char* value(const  ::irobot_create_2_1::BrakeRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x691501d2b5eb4dc0ULL;
  static const uint64_t static_value2 = 0x1a97397d7baf5fbaULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_create_2_1::BrakeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_create_2_1/BrakeRequest";
  }

  static const char* value(const  ::irobot_create_2_1::BrakeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::irobot_create_2_1::BrakeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool brake\n\
\n\
";
  }

  static const char* value(const  ::irobot_create_2_1::BrakeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::irobot_create_2_1::BrakeRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::irobot_create_2_1::BrakeResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::irobot_create_2_1::BrakeResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::irobot_create_2_1::BrakeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::irobot_create_2_1::BrakeResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::irobot_create_2_1::BrakeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_create_2_1/BrakeResponse";
  }

  static const char* value(const  ::irobot_create_2_1::BrakeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::irobot_create_2_1::BrakeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::irobot_create_2_1::BrakeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::irobot_create_2_1::BrakeResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::irobot_create_2_1::BrakeRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.brake);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BrakeRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::irobot_create_2_1::BrakeResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BrakeResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<irobot_create_2_1::Brake> {
  static const char* value() 
  {
    return "c154fccc169551daeea068d31d0a6b63";
  }

  static const char* value(const irobot_create_2_1::Brake&) { return value(); } 
};

template<>
struct DataType<irobot_create_2_1::Brake> {
  static const char* value() 
  {
    return "irobot_create_2_1/Brake";
  }

  static const char* value(const irobot_create_2_1::Brake&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<irobot_create_2_1::BrakeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c154fccc169551daeea068d31d0a6b63";
  }

  static const char* value(const irobot_create_2_1::BrakeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<irobot_create_2_1::BrakeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_create_2_1/Brake";
  }

  static const char* value(const irobot_create_2_1::BrakeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<irobot_create_2_1::BrakeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c154fccc169551daeea068d31d0a6b63";
  }

  static const char* value(const irobot_create_2_1::BrakeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<irobot_create_2_1::BrakeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "irobot_create_2_1/Brake";
  }

  static const char* value(const irobot_create_2_1::BrakeResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // IROBOT_CREATE_2_1_SERVICE_BRAKE_H

